[package]
name = "weather-app"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json","blocking"]}
serde_json = "1.0.128"
serde={version = "1.0.210", features = ["derive"]}
